import { ScrapedDataResponse } from '@/types';

export const defaultFullData: ScrapedDataResponse = {
  isLiveSynced: true,
  lastSyncedAt: new Date().toISOString(),
  bio: {
    name: 'Tarun Singh',
    title: 'Founder & Lead Developer',
    company: 'TK Web Solutions',
    phone: '+91 90793 68240',
    email: 'tkwebsolution1301@gmail.com',
    location: 'Bharatpur, Rajasthan, India',
    whatsapp: 'https://wa.me/919079368240',
    instagram: 'https://www.instagram.com/tkwebsolutions_official',
    telegram: 'https://t.me/TKwebsolutions_bot',
    github: 'https://github.com/Tarunsinghgunesh',
    summary: 'Founder of TK Web Solutions, developer, product builder, and BBA Digital Marketing student at Manipal University Jaipur. Architecting next-gen websites, native Android APKs, 3D WebGL experiences, and AI/ML-driven digital products with 100% precision, clean codebases, and top-ranking Google SEO.',
    experienceYears: 'Founder & Full-Stack Architect',
    projectsCompleted: '9 Live Apps & Sites',
    clientSatisfaction: '100% Verified',
    skills: [
      { name: 'Next.js 14 & React 19', level: 96, category: 'Frontend' },
      { name: 'Three.js & 3D WebGL', level: 94, category: '3D & UI' },
      { name: 'AI / Machine Learning (LM/ML)', level: 88, category: 'Backend' },
      { name: 'Flutter 3.19+ & Dart', level: 92, category: 'Mobile' },
      { name: 'Android Studio & APK Builds', level: 95, category: 'Mobile' },
      { name: 'Isar NoSQL & Supabase Realtime', level: 90, category: 'Backend' },
      { name: 'Google Schema.org & Local SEO', level: 98, category: 'Frontend' },
      { name: 'Tailwind CSS & Framer Motion', level: 98, category: '3D & UI' },
    ],
  },
  projects: [
    {
      id: 'luna-sanctuary',
      title: 'Luna — Companion & Period Sanctuary',
      category: 'Flutter',
      description: 'Officially launched on 1 Sep 2026 at 11:11 AM IST! High-fidelity cycle sanctuary with privacy-first offline Isar local storage, Supabase Realtime partner syncing, zero data leaks, zero ads, and zero subscriptions.',
      techStack: ['Flutter 3.19+', 'Dart', 'Riverpod', 'Isar NoSQL', 'Supabase Realtime'],
      liveUrl: 'https://luna-website-flame.vercel.app/',
      githubUrl: 'https://github.com/Tarunsinghgunesh/Luna-companion-period-sanctuary',
      downloadUrl: 'https://luna-website-flame.vercel.app/',
      status: 'Live',
      featured: true,
      metrics: [
        { label: 'Official Launch', value: '1 Sep 2026, 11:11 AM' },
        { label: 'Privacy Core', value: '100% Private (Isar)' },
        { label: 'Sync Engine', value: 'Supabase Realtime' },
        { label: 'Cost', value: '100% Free Forever' },
      ],
    },
    {
      id: 'chirag-handlooms',
      title: 'Chirag Handlooms E-Commerce Store',
      category: 'E-Commerce',
      description: 'Luxury handloom and textile shopping platform with 8 dynamic product categories, direct WhatsApp ordering engine, Google Maps integration, and Royal Blue design.',
      techStack: ['HTML5', 'CSS3', 'JavaScript', 'WhatsApp API', 'SEO'],
      liveUrl: 'https://tarunsinghgunesh.github.io/chirag-handlooms-e-commerce-/',
      githubUrl: 'https://github.com/Tarunsinghgunesh/chirag-handlooms-e-commerce-',
      status: 'Live',
      featured: true,
      metrics: [
        { label: 'Categories', value: '8 Active' },
        { label: 'Orders', value: 'Direct WhatsApp' },
        { label: 'Speed', value: '< 1s CDN' },
      ],
    },
    {
      id: 'achievers-point',
      title: 'Achievers Point Coaching Portal',
      category: 'Coaching',
      description: 'Premier coaching institute platform for IIT-JEE, NEET, and NDA aspirants featuring batch schedules, verified results showcase, fee structure, and direct inquiry gateway.',
      techStack: ['HTML5', 'CSS3', 'JavaScript', 'Lead Engine', 'Schema.org'],
      liveUrl: 'https://tarunsinghgunesh.github.io/ACHIEVERSPOINT/',
      githubUrl: 'https://github.com/Tarunsinghgunesh/ACHIEVERSPOINT',
      status: 'Live',
      featured: true,
      metrics: [
        { label: 'Programs', value: 'IIT / NEET / NDA' },
        { label: 'Inquiries', value: 'Direct Lead Sync' },
        { label: 'SEO Rank', value: 'Local #1' },
      ],
    },
    {
      id: 'tk-official-app',
      title: 'TK Web Solutions Official Studio APK',
      category: 'Android APK',
      description: 'Official direct-install Android application showcasing real-time agency services, cost estimators, project portfolios, and direct founder chat for clients.',
      techStack: ['Android Studio', 'Java / Kotlin', 'WebView / APK', 'Offline Cache'],
      downloadUrl: 'https://tkwebsolutions.in/app/TKWebSolutions.apk',
      liveUrl: 'https://tkwebsolutions.in/',
      status: 'Live',
      featured: true,
      metrics: [
        { label: 'Compatibility', value: 'Android 5.0+' },
        { label: 'Distribution', value: 'Direct APK Download' },
        { label: 'Size', value: 'Lightweight APK' },
      ],
    },
    {
      id: 'eduprime-app',
      title: 'EduPrime Smart Learning App',
      category: 'Android APK',
      description: 'Native Android coaching and learning application with live lecture access, study materials, student notices, and attendance records.',
      techStack: ['Android SDK', 'Java / Kotlin', 'Firebase DB', 'Direct APK'],
      downloadUrl: 'https://tkwebsolutions.in/app/EduPrime.apk',
      liveUrl: 'https://tkwebsolutions.in/',
      status: 'Live',
      featured: true,
      metrics: [
        { label: 'Target', value: 'Coaching Students' },
        { label: 'Delivery', value: 'Direct APK Install' },
        { label: 'Security', value: 'Encrypted Access' },
      ],
    },
    {
      id: 'ek-pahal-india',
      title: 'Ek Pahal India NGO Platform',
      category: 'Govt',
      description: 'Comprehensive NGO web platform empowering student education with verified impact metrics, volunteer onboarding forms, and transparent donation details.',
      techStack: ['HTML5', 'CSS3', 'JavaScript', 'Forms Engine', 'Responsive'],
      liveUrl: 'https://tarunsinghgunesh.github.io/ekpahalindia/',
      githubUrl: 'https://github.com/Tarunsinghgunesh/ekpahalindia',
      status: 'Live',
      featured: false,
      metrics: [
        { label: 'Mission', value: 'Student Education' },
        { label: 'Impact', value: 'Verified Stats' },
      ],
    },
    {
      id: 'dhruv-emitra',
      title: 'Dhruv E-Mitra Seva Kendra',
      category: 'Govt',
      description: 'Citizen digital services portal with complete government service listings, UPI QR code instant payments, status checking, and Google Maps location.',
      techStack: ['HTML5', 'CSS3', 'JavaScript', 'UPI Payment QR', 'Google Maps'],
      liveUrl: 'https://tarunsinghgunesh.github.io/dhruvemitrasevakendra/',
      githubUrl: 'https://github.com/Tarunsinghgunesh/dhruvemitrasevakendra',
      status: 'Live',
      featured: false,
      metrics: [
        { label: 'Payments', value: 'Instant UPI QR' },
        { label: 'Services', value: 'Govt E-Mitra' },
      ],
    },
    {
      id: 'new-tagore-school',
      title: 'New Tagore Public School',
      category: 'School',
      description: 'Official school web portal featuring online admission applications, academic calendars, fee structures, faculty profiles, and 100% board examination results showcase.',
      techStack: ['HTML5', 'CSS3', 'JavaScript', 'Admissions Form', 'SEO'],
      liveUrl: 'https://tarunsinghgunesh.github.io/New-tagore-public-school/',
      githubUrl: 'https://github.com/Tarunsinghgunesh/New-tagore-public-school',
      status: 'Live',
      featured: false,
      metrics: [
        { label: 'Results', value: '100% Pass Record' },
        { label: 'Portal', value: 'Online Admissions' },
      ],
    },
    {
      id: 'support-small-business',
      title: 'Support Small Business Rajasthan',
      category: 'Website',
      description: 'Digital directory and promotion platform designed for local Bharatpur merchants and services to establish their online presence and receive inquiries.',
      techStack: ['HTML5', 'CSS3', 'JavaScript', 'SEO Schema', 'Local Search'],
      liveUrl: 'https://tarunsinghgunesh.github.io/support_small_business/',
      githubUrl: 'https://github.com/Tarunsinghgunesh/support_small_business',
      status: 'Live',
      featured: false,
      metrics: [
        { label: 'Directory', value: 'Local Bharatpur' },
        { label: 'Reach', value: 'WhatsApp Direct' },
      ],
    },
  ],
  services: [
    {
      id: 'coaching-web',
      title: 'Coaching Institute Website',
      shortDesc: 'Batches, results, fee structures, faculty pages, inquiry forms, and Google #1 SEO ranking.',
      fullDesc: 'Custom-built for coaching institutes in Bharatpur and across India. Complete batch manager, topper results gallery, WhatsApp inquiry button, and 30-day founder support.',
      price: '₹14,999',
      deliveryTime: '5–7 Days',
      icon: 'GraduationCap',
      badge: 'Most Popular',
      features: [
        'Mobile-First 60FPS Responsive Design',
        'Batch Timetable & Fee Structure Showcase',
        'Direct WhatsApp Lead Capture',
        'Google LocalBusiness Schema SEO',
      ],
    },
    {
      id: 'android-apk',
      title: 'Installable Android APK App',
      shortDesc: 'Custom Android application that installs directly on phones without Play Store friction.',
      fullDesc: 'Lightweight, lightning-fast Android APK shareable over WhatsApp or downloaded directly from your website. Built with Android Studio and offline cache.',
      price: '₹14,999',
      deliveryTime: '5–7 Days',
      icon: 'Smartphone',
      badge: 'Fast Delivery',
      features: [
        'Direct Phone Installation (APK File)',
        'Shareable via WhatsApp & Website',
        'Android 5.0 to 14+ Compatibility',
        'Offline Data Caching & Push Alerts',
      ],
    },
    {
      id: 'business-web',
      title: 'Business & Corporate Website',
      shortDesc: 'High-converting business website with contact forms, Google Maps, and lead engines.',
      fullDesc: 'Professional multi-page website architected to turn local visitors into paying customers. Equipped with SEO metadata and modern animations.',
      price: '₹17,999',
      deliveryTime: '5–7 Days',
      icon: 'Briefcase',
      features: [
        'High-Conversion Landing Page Architecture',
        'Google Maps & One-Click Call/WhatsApp',
        'Custom Service Catalogs & Testimonials',
        'Free Domain & CDN Setup Support',
      ],
    },
    {
      id: 'ecommerce-web',
      title: 'E-Commerce & WhatsApp Store',
      shortDesc: 'Product catalog with WhatsApp ordering, category filtering, and UPI payment integration.',
      fullDesc: 'Sell products online with zero recurring commissions. Includes categorized catalog, WhatsApp instant cart ordering, and Razorpay/UPI gateway integration.',
      price: '₹19,999',
      deliveryTime: '5–7 Days',
      icon: 'ShoppingBag',
      features: [
        'Unlimited Product Showcase & Categories',
        'One-Click WhatsApp Cart Checkout',
        'UPI & Payment Gateway Integration',
        'Mobile-Optimized Fast Product Pages',
      ],
    },
    {
      id: 'school-web',
      title: 'School & College Portal',
      shortDesc: 'Admission forms, notice boards, event galleries, and staff directories.',
      fullDesc: 'Comprehensive institutional portal with online admission forms, academic calendar, annual results gallery, and parent inquiry gateway.',
      price: '₹19,999',
      deliveryTime: '5–7 Days',
      icon: 'School',
      features: [
        'Online Student Admission Forms',
        'Notice Board & Events Calendar',
        'Faculty & Staff Directory',
        '100% Board Results Showcase',
      ],
    },
    {
      id: 'playstore-app',
      title: 'Google Play Store Official App',
      shortDesc: 'Full Android application published and live on the Google Play Store.',
      fullDesc: 'Published on Google Play with custom icon, screenshots, store listing optimization, and push notifications for maximum brand prestige.',
      price: '₹24,999',
      deliveryTime: '7–10 Days',
      icon: 'PlaySquare',
      features: [
        'Official Google Play Store Publishing',
        'App Store Optimization (ASO)',
        'Push Notification Infrastructure',
        'Firebase Analytics & Crash Reporting',
      ],
    },
    {
      id: 'dual-app',
      title: 'Android + iOS Dual Cross-Platform App',
      shortDesc: 'Unified Flutter / React Native codebase published on Play Store & Apple App Store.',
      fullDesc: 'Flagship cross-platform mobile application delivering identical 60 FPS performance on both Android and iOS devices with shared backend.',
      price: '₹44,999',
      deliveryTime: '10–15 Days',
      icon: 'Layers',
      features: [
        'Google Play Store + Apple App Store Setup',
        'Flutter 3.19+ / Riverpod Native Performance',
        'Supabase / Firebase Realtime Backend',
        '60 FPS Smooth Custom UI Components',
      ],
    },
  ],
  pricingPlans: [
    {
      id: 'starter',
      name: 'Starter Website',
      subtitle: 'Ideal for small businesses, doctors, personal portfolios & local shops.',
      price: 14999,
      priceFormatted: '₹14,999',
      deliveryDays: '5–7 Days',
      category: 'web',
      features: [
        '5 Custom Designed Pages',
        'Mobile & Desktop 60FPS Responsive',
        'Direct WhatsApp & Call Integration',
        'Google Maps & Contact Form',
        'Google LocalBusiness Schema SEO',
        '30 Days Free Technical Support',
      ],
    },
    {
      id: 'business',
      name: 'Business & Coaching Package',
      subtitle: 'Complete flagship solution for coaching institutes, schools & growing enterprises.',
      price: 19999,
      priceFormatted: '₹19,999 – ₹29,999',
      deliveryDays: '5–7 Days',
      popular: true,
      category: 'web',
      features: [
        'Up to 10 Custom Pages & Batches',
        'Interactive Topper Results / Gallery',
        'Lead Capture Engine with Email Alerts',
        'Top-Rank Google SEO & Schema.org',
        'High-Speed CDN & SSL Certificate Setup',
        '30 Days Dedicated Founder Support',
      ],
    },
    {
      id: 'apk-app',
      name: 'Android APK App',
      subtitle: 'Direct installable mobile app shareable on WhatsApp without Play Store fees.',
      price: 14999,
      priceFormatted: '₹14,999',
      deliveryDays: '5–7 Days',
      category: 'app',
      features: [
        'Direct Installable Android APK File',
        'Direct Download Link on Website',
        'Shareable via WhatsApp with One Click',
        'Offline Data Cache & Push Alerts',
        'Android 5.0 to 14+ Compatibility',
        '30 Days Free Technical Support',
      ],
    },
    {
      id: 'playstore',
      name: 'Play Store App Package',
      subtitle: 'Official Android application published on the Google Play Store.',
      price: 24999,
      priceFormatted: '₹24,999',
      deliveryDays: '7–10 Days',
      category: 'app',
      features: [
        'Published on Google Play Store',
        'App Icon, Screenshots & Store Listing',
        'Firebase Push Notifications & Analytics',
        'Fast 60FPS Fluid Native UI',
        'Complete Source Code Handover',
        '30 Days Free Support Guarantee',
      ],
    },
    {
      id: 'dual-flagship',
      name: 'Android + iOS Dual Flagship',
      subtitle: 'Cross-platform Flutter application for Android Play Store & Apple App Store.',
      price: 44999,
      priceFormatted: '₹44,999',
      deliveryDays: '10–15 Days',
      category: 'combo',
      features: [
        'Google Play Store + Apple App Store',
        'Flutter 3.19+ Cross-Platform Engine',
        'Supabase / Firebase Realtime Database',
        'Push Notifications & User Auth',
        'Razorpay Payment Gateway Integration',
        '30 Days Priority Founder Support',
      ],
    },
  ],
  testimonials: [],
};
